### ISSUE TITLE
External Page: Unable to pair Trust wallet via wallet connect

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/foxfarm#76]
Description:
cannot pair Trust wallet via Wallet connect to https://fox.shapeshift.com/fox-farming. I also tried to use incognito window and it is the same. After scanning the qr code, it would try to connect for several seconds and then the error messages "expected http 101 response but was "522 origin connection time-out" or "an unknown error occurred" comes up. I tried to connect via wallet connect to other sites like Uniswap and it works fine.
 
Recreate:
* Visit: https://fox.shapeshift.com/fox-farming
* Select "connect Wallet" and select "Wallet Connect"
* Scan QR code
* Wallet does not connect, notice error messaging
 
Link:
https://discord.com/channels/554694662431178782/873244924026449940/902890083336728656
 
A/C:
Trust Wallet/Wallet Connect will connect to the external https://fox.shapeshift.com/fox-farming page

**Comment by SS-FOX-McCloud** [comment]
@0xean this might be a good bounty

**Comment by purelycrickets** [comment]
Additionally, Guarda wallet has been reported in Discord to also suffer the same connectivity issues with wallet connect
